[package]
name = "simple-restaurant-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
